name: Semantic Versioning
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
jobs:
  build_release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          enable_prerelease_mode: true

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true
