jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Semantic release
        run: yarn semantic-release

name: Semantic release
on:
  push:
    branches:
      - master
      - release/*
      - hotfix/*
